M48
; DRILL file {KiCad 7.0.7} date Mon Nov 13 23:42:34 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-13T23:42:34-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1160
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T1
X4.9968Y-2.7032
X5.0Y-1.2
X7.0Y-1.2
X7.0Y-2.7
T2
X5.0148Y-1.5007
X5.0148Y-1.8007
X5.0148Y-2.0007
X5.0148Y-2.4007
T3
X5.643Y-2.7359
T0
M30
