M48
; DRILL file {KiCad 7.0.7} date Mon Nov  6 00:52:26 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-06T00:52:26-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X3.06Y-2.5594
T2
X2.43Y-1.5
X2.43Y-1.8
X2.43Y-2.1
X2.43Y-2.5
T0
M30
