M48
; DRILL file {KiCad 7.0.7} date Mon Nov  6 08:22:06 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-06T08:22:06-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1160
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1358
%
G90
G05
T1
X4.9968Y-2.7032
X5.0Y-1.2
X7.0Y-1.2
X7.0Y-2.7
T2
X5.6448Y-2.5102
T3
X5.0148Y-1.5007
X5.0148Y-1.8007
X5.0148Y-2.0007
X5.0148Y-2.4007
T0
M30
